# docker-compose.yml
version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://node_user:node_password@postgres:5432/monstersdb
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - '35432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: node_user
      POSTGRES_PASSWORD: node_password
      POSTGRES_DB: monstersdb
